<?php

namespace App\Http\Controllers;

use App\Models\Url;
use Carbon\Carbon;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Http\Response;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\View\View;

class UrlController extends Controller
{
    public function requestGenerate(Request $request): RedirectResponse
    {
        $user = $request->user();
        $roleName = DB::table('roles')->where('id', $user->role_id)->value('name');

        abort_unless(in_array($roleName, ['Admin', 'Member'], true), 403);

        $data = $request->validate([
            'original_url' => ['required', 'string', 'max:2000'],
        ]);

        $originalUrl = trim($data['original_url']);
        if (! filter_var($originalUrl, FILTER_VALIDATE_URL)) {
            return back()->withErrors([
                'original_url' => 'Please enter a valid full URL (including http:// or https://).',
            ])->withInput();
        }

        $code = $this->generateUniqueCode();

        $url = Url::query()->create([
            'company_id' => $user->company_id,
            // system flow, but keep requester attribution for visibility rules
            'created_by' => $user->id,
            'original_url' => $originalUrl,
            // keeping this simple for assignment scope
            'short_code' => $code,
        ]);

        return back()
            ->with('status', 'URL generated by system.')
            ->with('short_url', route('urls.resolve', ['code' => $url->short_code]));
    }

    public function index(Request $request): View
    {
        $this->authorize('viewAny', Url::class);

        $user = $request->user();
        $roleName = DB::table('roles')->where('id', $user->role_id)->value('name');
        $interval = (string) $request->query('interval', 'all');

        $query = Url::query()->with('creator');

        $this->applyVisibilityScope($query, $roleName, $user->company_id, $user->id);
        $this->applyDateIntervalScope($query, $interval);

        $urls = $query->latest()->paginate(10)->withQueryString();

        return view('urls.index', [
            'urls' => $urls,
            'roleName' => $roleName,
            'interval' => $interval,
        ]);
    }

    public function downloadCsv(Request $request): Response
    {
        $this->authorize('viewAny', Url::class);

        $user = $request->user();
        $roleName = DB::table('roles')->where('id', $user->role_id)->value('name');
        $interval = (string) $request->query('interval', 'all');

        $query = Url::query()->with(['creator', 'company']);
        $this->applyVisibilityScope($query, $roleName, $user->company_id, $user->id);
        $this->applyDateIntervalScope($query, $interval);

        $rows = $query->latest()->get();

        $csv = [];
        $csv[] = implode(',', ['Short URL', 'Long URL', 'Hits', 'Created By', 'Company', 'Created At']);

        foreach ($rows as $url) {
            $csv[] = implode(',', [
                $this->csvCell(route('urls.resolve', ['code' => $url->short_code])),
                $this->csvCell($url->original_url),
                (string) ($url->hits ?? 0),
                $this->csvCell($url->creator?->name ?? 'System'),
                $this->csvCell($url->company?->name ?? '-'),
                $this->csvCell((string) $url->created_at),
            ]);
        }

        $filename = 'urls_'.$interval.'_'.now()->format('Ymd_His').'.csv';

        return response(implode("\n", $csv), 200, [
            'Content-Type' => 'text/csv; charset=UTF-8',
            'Content-Disposition' => 'attachment; filename="'.$filename.'"',
        ]);
    }

    public function resolve(Request $request, string $code): RedirectResponse
    {
        $url = Url::query()->where('short_code', $code)->firstOrFail();

        try {
            $this->authorize('view', $url);
        } catch (AuthorizationException) {
            // strict mode: do not reveal if code exists
            abort(404);
        }

        // count successful private short URL opens
        $url->increment('hits');

        return redirect()->away($url->original_url);
    }

    private function generateUniqueCode(): string
    {
        $length = (int) config('shortener.code_length', 8);
        $attempts = (int) config('shortener.max_generate_attempts', 10);

        for ($i = 0; $i < $attempts; $i++) {
            $candidate = Str::lower(Str::random($length));
            $exists = Url::query()->where('short_code', $candidate)->exists();

            if (! $exists) {
                return $candidate;
            }
        }

        abort(500, 'Could not generate unique short code.');
    }

    private function applyVisibilityScope($query, string $roleName, int $companyId, int $userId): void
    {
        // keeping this simple for assignment scope
        if ($roleName === 'SuperAdmin') {
            return;
        }

        if ($roleName === 'Admin') {
            $query->where('company_id', '=', $companyId);

            return;
        }

        if ($roleName === 'Member') {
            $query->where('created_by', '=', $userId);

            return;
        }

        $query->whereRaw('1 = 0');
    }

    private function applyDateIntervalScope($query, string $interval): void
    {
        $now = Carbon::now();

        if ($interval === 'today') {
            $query->whereBetween('created_at', [$now->copy()->startOfDay(), $now]);

            return;
        }

        if ($interval === 'last_week') {
            $query->whereBetween('created_at', [$now->copy()->subDays(7), $now]);

            return;
        }

        if ($interval === 'last_month') {
            $query->whereBetween('created_at', [
                $now->copy()->subMonthNoOverflow()->startOfMonth(),
                $now->copy()->subMonthNoOverflow()->endOfMonth(),
            ]);

            return;
        }

        if ($interval === 'this_month') {
            $query->whereBetween('created_at', [$now->copy()->startOfMonth(), $now]);
        }
    }

    private function csvCell(string $value): string
    {
        $escaped = str_replace('"', '""', $value);

        return '"'.$escaped.'"';
    }
}
